version: '3.8'

# A quick Wireguard setup with PiHole!
services:
  wg-zero:
    image: jasoryeh/wg-zero
    container_name: wg-zero
    ports:
      - "51820:51820/udp"
      - "51820:51820/tcp"
      - "51821:51821/tcp"
    environment:
      - WG_PORT=51820
      - PORT=51821
      - WG_HOST=${HOST_IP} # FILL THIS WITH YOUR PUBLIC IP, or auto fill it by passing it to compose as an environment var using a IP service of your choice
      - PASSWORD=password
      # Point WireGuard clients to use Pi-hole for DNS
      - WG_DEFAULT_DNS=10.2.0.3
      #- WG_DEFAULT_ALLOWED_IPS=10.2.0.0/24 # for VPN-only networking (if you just want a virtual network and not internet)
      - WG_DEFAULT_ALLOWED_IPS=0.0.0.0/0 # for all internet
      - ./mount/etc-wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.2.0.2

  pihole:
    container_name: vpn-pihole
    image: pihole/pihole:latest
    ports:
    #  - "5353:53/tcp"
    #  - "5353:53/udp"
      - "8083:80/tcp"  # Web interface
    environment:
      TZ: 'America/Los_Angeles'  # Change this to your timezone
      FTLCONF_webserver_api_password: password  # Change this to a secure password
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
      - './mount/etc-pihole:/etc/pihole'
      - './mount/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 10.2.0.3
    stop_grace_period: 1s

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
